---
name: juvix-ci-build-pr
kind: pipeline
node:
  project: juvix
steps:
- name: download-scripts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 cp s3://$S3_BUCKET_SCRIPTS/juvix.zip scripts/ci/juvix.zip
  - cd scripts/ci && unzip juvix.zip
  environment:
    S3_BUCKET_SCRIPTS: drone-ci-scripts
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
- name: test-suite
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make stack-yaml
  - make update-local-stdlibs
  - make test
  depends_on:
  - download-scripts
- name: test-parser
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-parser
  depends_on:
  - test-suite
- name: test-typecheck
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-typecheck
  depends_on:
  - test-suite
- name: test-compile
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-compile
  depends_on:
  - test-suite
- name: org-generation-and-code-formatting
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - sh ./scripts/ci/format-and-org-gen.sh
  depends_on:
  - test-typecheck
  - test-compile
  - test-parser
- name: build-checksums
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - python3 scripts/ci/generate-checksums.py
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  depends_on:
  - test-typecheck
  - test-compile
  - test-parser
- name: push-changes
  image: openanalytics/alpine-git-lfs-client
  pull: never
  commands:
  - sh ./scripts/ci/push-changes.sh
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  depends_on:
  - org-generation-and-code-formatting
  - build-checksums
trigger:
  event:
  - pull_request
type: docker
workspace:
  path: /juvix/workspace
environment:
  GIT_LFS_SKIP_SMUDGE: '1'
  STACK_ROOT: /juvix/workspace/.stack
---
name: juvix-ci-build-push-develop
kind: pipeline
node:
  project: juvix
steps:
- name: download-scripts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 cp s3://$S3_BUCKET_SCRIPTS/juvix.zip scripts/ci/juvix.zip
  - cd scripts/ci && unzip juvix.zip
  environment:
    S3_BUCKET_SCRIPTS: drone-ci-scripts
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
- name: test-suite
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make stack-yaml
  - make update-local-stdlibs
  - make test
  depends_on:
  - download-scripts
- name: test-parser
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-parser
  depends_on:
  - test-suite
- name: test-typecheck
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-typecheck
  depends_on:
  - test-suite
- name: test-compile
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-compile
  depends_on:
  - test-suite
trigger:
  event:
  - push
  branch:
  - develop
type: docker
workspace:
  path: /juvix/workspace
environment:
  GIT_LFS_SKIP_SMUDGE: '1'
  STACK_ROOT: /juvix/workspace/.stack
---
name: juvix-ci-docs-pr-push-develop
kind: pipeline
node:
  project: juvix
steps:
- name: download-scripts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 cp s3://$S3_BUCKET_SCRIPTS/juvix.zip scripts/ci/juvix.zip
  - cd scripts/ci && unzip juvix.zip
  environment:
    S3_BUCKET_SCRIPTS: drone-ci-scripts
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
- name: restore-cache-michelson
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Backends/Michelson/stack.yaml" }}
    mount:
    - library/Backends/Michelson/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-parsing
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Parsing/stack.yaml" }}
    mount:
    - library/Parsing/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-core
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Core/stack.yaml" }}
    mount:
    - library/Core/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-standard-library
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/StandardLibrary/stack.yaml" }}
    mount:
    - library/StandardLibrary/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-witch
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Witch/stack.yaml" }}
    mount:
    - library/Witch/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-context
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Context/stack.yaml" }}
    mount:
    - library/Context/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-sexp
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Sexp/stack.yaml" }}
    mount:
    - library/Sexp/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-translate
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Translate/stack.yaml" }}
    mount:
    - library/Translate/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-easy
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Playground/Easy/stack.yaml" }}
    mount:
    - library/Playground/Easy/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-data-structure
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Test/DataStructures/stack.yaml" }}
    mount:
    - library/Test/DataStructures/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: restore-cache-llvm
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Backends/LLVM/stack.yaml" }}
    mount:
    - library/Backends/LLVM/.stack-work
    override: false
    region: eu-west-1
    rebuild: false
    restore: true
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 16m
  depends_on:
  - download-scripts
  when:
    status:
    - success
    - failure
- name: build-docs
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - ./scripts/ci/build-and-publish-docs.sh
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  depends_on:
  - restore-cache-context
  - restore-cache-core
  - restore-cache-data-structure
  - restore-cache-easy
  - restore-cache-parsing
  - restore-cache-llvm
  - restore-cache-michelson
  - restore-cache-sexp
  - restore-cache-standard-library
  - restore-cache-translate
  - restore-cache-witch
- name: rebuild-cache-michelson
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Backends/Michelson/stack.yaml" }}
    mount:
    - library/Backends/Michelson/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-parsing
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Parsing/stack.yaml" }}
    mount:
    - library/Parsing/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-core
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Core/stack.yaml" }}
    mount:
    - library/Core/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-standard-library
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/StandardLibrary/stack.yaml" }}
    mount:
    - library/StandardLibrary/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-witch
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Witch/stack.yaml" }}
    mount:
    - library/Witch/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-context
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Context/stack.yaml" }}
    mount:
    - library/Context/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-sexp
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Sexp/stack.yaml" }}
    mount:
    - library/Sexp/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-translate
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Translate/stack.yaml" }}
    mount:
    - library/Translate/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-easy
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Playground/Easy/stack.yaml" }}
    mount:
    - library/Playground/Easy/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-data-structure
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Test/DataStructures/stack.yaml" }}
    mount:
    - library/Test/DataStructures/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 8m
  depends_on:
  - build-docs
  when:
    status:
    - success
- name: rebuild-cache-llvm
  image: meltwater/drone-cache:latest
  pull: never
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: juvix/docs/{{ checksum "library/Backends/LLVM/stack.yaml" }}
    mount:
    - library/Backends/LLVM/.stack-work
    override: false
    region: eu-west-1
    rebuild: true
    restore: false
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    BACKEND_OPERATION_TIMEOUT: 16m
  depends_on:
  - build-docs
  when:
    status:
    - success
trigger:
  event:
  - push
  - pull_request
  branch:
  - develop
type: docker
workspace:
  path: /juvix/docs
environment:
  GIT_LFS_SKIP_SMUDGE: '1'
  STACK_ROOT: /juvix/docs/.stack
---
name: juvix-ci-update-artifacts-push-develop
kind: pipeline
node:
  project: juvix
steps:
- name: download-scripts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 cp s3://$S3_BUCKET_SCRIPTS/juvix.zip scripts/ci/juvix.zip
  - cd scripts/ci && unzip juvix.zip
  environment:
    S3_BUCKET_SCRIPTS: drone-ci-scripts
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
- name: upload-artifacts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 sync stdlib s3://heliax-juvix-artifacts-v1 --acl public-read --exclude
    "*" --include "*.json" --include "*/*.ju" --include "*.ju"
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  depends_on:
  - download-scripts
trigger:
  event:
  - push
  branch:
  - develop
type: docker
workspace:
  path: /juvix/workspace
environment:
  GIT_LFS_SKIP_SMUDGE: '1'
  STACK_ROOT: /juvix/workspace/.stack
---
kind: signature
hmac: 218fbc5591d4577e3ab7fc9f06cced2eeae44516a92fab3bea361734f5b62010

...
