---
name: juvix-ci-build-pr
kind: pipeline
node:
  project: juvix
steps:
- name: download-scripts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 cp s3://$S3_BUCKET_SCRIPTS/juvix.zip scripts/ci/juvix.zip
  - cd scripts/ci && unzip juvix.zip
  environment:
    S3_BUCKET_SCRIPTS: drone-ci-scripts
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
- name: test-suite
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make stack-yaml
  - make update-local-stdlibs
  - make test
  depends_on:
  - download-scripts
- name: test-parser
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-parser
  depends_on:
  - test-suite
- name: test-typecheck
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-typecheck
  depends_on:
  - test-suite
- name: test-compile
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-compile
  depends_on:
  - test-suite
- name: org-generation-and-code-formatting
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - sh ./scripts/ci/format-and-org-gen.sh
  depends_on:
  - test-typecheck
  - test-compile
  - test-parser
- name: build-checksums
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - python3 scripts/ci/generate-checksums.py
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  depends_on:
  - test-typecheck
  - test-compile
  - test-parser
- name: push-changes
  image: openanalytics/alpine-git-lfs-client
  pull: never
  commands:
  - sh ./scripts/ci/push-changes.sh
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  depends_on:
  - org-generation-and-code-formatting
  - build-checksums
trigger:
  event:
  - pull_request
type: docker
workspace:
  path: /juvix/workspace
environment:
  GIT_LFS_SKIP_SMUDGE: '1'
  STACK_ROOT: /juvix/workspace/.stack
---
name: juvix-ci-build-push-develop
kind: pipeline
node:
  project: juvix
steps:
- name: download-scripts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 cp s3://$S3_BUCKET_SCRIPTS/juvix.zip scripts/ci/juvix.zip
  - cd scripts/ci && unzip juvix.zip
  environment:
    S3_BUCKET_SCRIPTS: drone-ci-scripts
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
- name: test-suite
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make stack-yaml
  - make update-local-stdlibs
  - make test
  depends_on:
  - download-scripts
- name: test-parser
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-parser
  depends_on:
  - test-suite
- name: test-typecheck
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-typecheck
  depends_on:
  - test-suite
- name: test-compile
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - make test-compile
  depends_on:
  - test-suite
trigger:
  event:
  - push
  branch:
  - develop
type: docker
workspace:
  path: /juvix/workspace
environment:
  GIT_LFS_SKIP_SMUDGE: '1'
  STACK_ROOT: /juvix/workspace/.stack
---
name: juvix-ci-docs-pr-push-develop
kind: pipeline
node:
  project: juvix
steps:
- name: download-scripts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 cp s3://$S3_BUCKET_SCRIPTS/juvix.zip scripts/ci/juvix.zip
  - cd scripts/ci && unzip juvix.zip
  environment:
    S3_BUCKET_SCRIPTS: drone-ci-scripts
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
- name: build-docs
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/juvix:latest
  pull: never
  commands:
  - ./scripts/ci/build-and-publish-docs.sh
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  depends_on:
  - download-scripts
trigger:
  event:
  - push
  - pull_request
  branch:
  - develop
type: docker
workspace:
  path: /juvix/docs
environment:
  GIT_LFS_SKIP_SMUDGE: '1'
  STACK_ROOT: /juvix/docs/.stack
---
name: juvix-ci-update-artifacts-push-develop
kind: pipeline
node:
  project: juvix
steps:
- name: download-scripts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 cp s3://$S3_BUCKET_SCRIPTS/juvix.zip scripts/ci/juvix.zip
  - cd scripts/ci && unzip juvix.zip
  environment:
    S3_BUCKET_SCRIPTS: drone-ci-scripts
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
- name: upload-artifacts
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/git:latest
  pull: never
  commands:
  - aws s3 sync stdlib s3://heliax-juvix-artifacts-v1 --acl public-read --exclude
    "*" --include "*.json" --include "*/*.ju" --include "*.ju"
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  depends_on:
  - download-scripts
trigger:
  event:
  - push
  branch:
  - develop
type: docker
workspace:
  path: /juvix/workspace
environment:
  GIT_LFS_SKIP_SMUDGE: '1'
  STACK_ROOT: /juvix/workspace/.stack
---
kind: signature
hmac: 3258fae691a2dbe4388f46130ab8d8ada8eb30447cb33791f68eb564ef2d6365

...
