name:                juvix
version:             0.1.1.19
github:              "anoma/juvix"
license:             GPL-3
homepage:            https://github.com/anoma/juvix#readme
synopsis:            Juvix smart contract language compiler, debugging toolkit, & stateful deployment system
category:            Web3
description:         Please see the README on GitHub at <https://github.com/anoma/juvix#readme>
author:              Heliax AG
maintainer:          cwgoes@heliax.dev, jeremy@heliax.dev, marty@heliax.dev, andy@heliax.dev
copyright:           2018 Christopher Goes, 2018-2019 Cryptium Labs, 2019- Heliax AG

extra-source-files:
- README.md

dependencies:
  - base >= 4.11 && < 5
  - directory
  - pretty-simple
  ###########################
  # Juvix Libraries
  ###########################
  - pipeline
  - standard-library
  - sexp
  - frontend
  - core
  - translate
  - witch
  - michelson
  - plonk
  - easy
  - llvm

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving
  - DefaultSignatures
  - QuasiQuotes
  - TypeOperators
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeInType
  - DerivingVia
  - TypeApplications
  - StandaloneDeriving
  - FunctionalDependencies
  - PatternSynonyms
  - TypeFamilies
  - ConstraintKinds
  - EmptyDataDeriving
  - TemplateHaskell
  - NamedFieldPuns
  - DisambiguateRecordFields
  - TupleSections
  - BlockArguments

when:
  condition: flag(incomplete-error)
  ghc-options:
    - -Werror=incomplete-patterns
    - -Werror=missing-fields
    - -Werror=missing-methods

flags:
  incomplete-error:
    description: >
      Incomplete patterns, missing record fields, and missing class methods are
      an error
    manual: true
    default: false

benchmarks:
  juvix-bench:
    main:         Main.hs
    source-dirs:  bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - juvix
      - criterion

library:
  source-dirs: src
  exposed-modules:
    - Juvix

executables:
  juvix:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ansi-wl-pprint
      - bytestring
      - base64-bytestring
      - github
      - gitrev
      - juvix
      - pretty-simple
      - optparse-applicative
