[tool.poetry]
authors = ["Gianmarco Fraccaroli <gianmarco.fraccaroli@gmail.com>"]
description = "update drone configuration signature"
name = "drone-signature-updater"
version = "0.1.0"

[tool.poetry.dependencies]
boto3 = "^1.17.84"
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
