name:                translate
version:             0.1.0.0
github:              "heliaxdev/juvix"
license:             GPL-3
author:              "Heliax AG <hello@heliax.dev>"
maintainer:          "Heliax AG <hello@heliax.dev>"
copyright:           "2020 Heliax AG"

description:         Please see the README on GitHub at <https://github.com/githubuser/Translate#readme>

dependencies:
- base >= 4.11 && < 5
- standard-library
- berlin-pipeline
- sexp
- parsing
- context
- unordered-containers
- stm-containers
- lens
- containers
- dlist
- syb
- megaparsec
- extra

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving
  - DefaultSignatures
  - QuasiQuotes
  - TypeOperators
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeInType
  - DerivingVia
  - TypeApplications
  - StandaloneDeriving
  - FunctionalDependencies
  - PatternSynonyms
  - TypeFamilies
  - ConstraintKinds
  - EmptyDataDeriving
  - TemplateHaskell
  - NamedFieldPuns
  - DisambiguateRecordFields
  - TupleSections
  - BlockArguments

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing
  - -fno-warn-missing-pattern-synonym-signatures
  - -j
  - -static
  - -fwrite-ide-info

library:
  source-dirs: src

tests:
  translate-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - filepath
    - megaparsec
    - pretty-simple
    - sexp
    - translate
    - tasty
    - tasty-hunit
    - context
    - data-structures
